In [26]:
%pylab inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


In [27]:
#populating the interactive namspace from numpy and matplotlib


In [28]:
beer = pd.read_csv('beer.txt', delimiter='\t')

In [29]:
beer.head()

Rank                                     Name  \
0     1                             Heady Topper   
1     2                        Pliny The Younger   
2     3                          Pliny The Elder   
3     4              Founders CBS Imperial Stout   
4     5  Founders KBS (Kentucky Breakfast Stout)   

                         Brewery            Type   ABV    WR  Reviews  
0                  The Alchemist    Imperial IPA   8.0  4.69     3146  
1  Russian River Brewing Company    Imperial IPA  11.0  4.65     1572  
2  Russian River Brewing Company    Imperial IPA   8.0  4.64     6129  
3       Founders Brewing Company  Imperial Stout  10.6  4.63     2026  
4       Founders Brewing Company  Imperial Stout  11.2  4.61     4714

In [30]:
#janitor work, lets get rid of the n/a's
beer = beer.dropna()

In [31]:
beer.shape

(234, 7)

In [32]:
# for classifitation we need labels
def good(x):
    if x>4.3:
        return 1
    else:
        return 0

# apply the function to the WR column
beer['Good']=beer['WR'].apply(good)

In [33]:
beer.head() # so you can call the function as you add a column!!!

Rank                                     Name  \
0     1                             Heady Topper   
1     2                        Pliny The Younger   
2     3                          Pliny The Elder   
3     4              Founders CBS Imperial Stout   
4     5  Founders KBS (Kentucky Breakfast Stout)   

                         Brewery            Type   ABV    WR  Reviews  Good  
0                  The Alchemist    Imperial IPA   8.0  4.69     3146     1  
1  Russian River Brewing Company    Imperial IPA  11.0  4.65     1572     1  
2  Russian River Brewing Company    Imperial IPA   8.0  4.64     6129     1  
3       Founders Brewing Company  Imperial Stout  10.6  4.63     2026     1  
4       Founders Brewing Company  Imperial Stout  11.2  4.61     4714     1

In [34]:
# create a logistic model instance
from sklearn import linear_model

logm = linear_model.LogisticRegression()

In [35]:
my_input = beer[['Reviews','ABV']].values
good_output = beer['Good'].values
good_output

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [36]:
# lets fit the model
logm.fit(my_input, good_output)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, penalty='l2', random_state=None, tol=0.0001)

In [37]:
logm.predict(my_input)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [38]:
logm.score(my_input, good_output)

0.62393162393162394

In [41]:
# lets change the penalty
logm2 = linear_model.LogisticRegression()
logm2.set_params(penalty='l2',dual=False)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, penalty='l2', random_state=None, tol=0.0001)

In [42]:
logm2.fit(my_input, good_output)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, penalty='l2', random_state=None, tol=0.0001)

In [45]:
logm2.predict(my_input)

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [47]:
logm2.score(my_input, good_output)

0.62393162393162394

In [48]:
pwd

u'/Users/nickroot'

In [49]:
beer

Rank                                          Name  \
0       1                                  Heady Topper   
1       2                             Pliny The Younger   
2       3                               Pliny The Elder   
3       4                   Founders CBS Imperial Stout   
4       5       Founders KBS (Kentucky Breakfast Stout)   
5       6                                   Zombie Dust   
7       8             Bourbon County Brand Coffee Stout   
8       9                                      Parabola   
9      10    Bourbon Barrel Aged Vanilla Bean Dark Lord   
10     11                                     The Abyss   
11     12                                  Supplication   
12     13                            Bell's Hopslam Ale   
13     14                          Cantillon Fou' Foune   
14     15                      Founders Breakfast Stout   
16     17                    Bourbon County Brand Stout   
17     18                                    Citra DIPA   
18     19                      Hunahpu's Imperial Stout   
19     20  Dark Horse Bourbon Barrel Aged Plead The 5th   
21     22                       Bell's Black Note Stout   
22     23       Kuhnhenn Bourbon Barrel Fourth Dementia   
23     24                                  Abrasive Ale   
24     25                                         Abner   
25     26                           Double Sunshine IPA   
26     27                                 Black Tuesday   
30     31                                      Darkness   
31     32                    Cantillon Lou Pepe - Kriek   
33     34                                 Double Galaxy   
34     35                               Dreadnaught IPA   
36     37                      Cantillon Saint Lamvinus   
37     38                  Everett PorterAmerican Porte   
..    ...                                           ...   
220   221                         Founders Red's Rye PA   
221   222                       Founders Double Trouble   
222   223                    Gulden Draak (Dark Triple)   
223   224                       Old Ruffian Barley Wine   
224   225                            YuleSmith (Summer)   
225   226                                  Black Albert   
226   227       The Angel's Share - Bourbon Barrel-Aged   
227   228                                    The Oracle   
228   229                                     Oude Tart   
229   230    Smuttynose Baltic Porter (Big Beer Series)   
230   231                             Dancing Man Wheat   
231   232                 Kuhnhenn Fourth Dementia (4D)   
232   233              Ivan The Terrible Imperial Stout   
233   234                      Kiwi Rising - Double IPL   
234   235                 Bourbon Abominable Winter Ale   
235   236                                   Compunction   
236   237                                     Baudoinia   
237   238                                   Hop Stoopid   
238   239                            Orval Trappist Ale   
239   240                       Bell's Expedition Stout   
240   241                    Great Lakes Blackout Stout   
241   242                                Obsidian Stout   
242   243                   Cantillon Kriek 100% Lambic   
243   244                                Apocalypse Cow   
244   245                Red Racer IPA (India Pale Ale)   
245   246                          Just Outstanding IPA   
246   247                              Allagash Odyssey   
247   248                                  Columbus IPA   
248   249                              Barrel Aged Yeti   
249   250                   Rye'da TigerAmerican Double   

                                Brewery                     Type    ABV    WR  \
0                         The Alchemist             Imperial IPA   8.00  4.69   
1         Russian River Brewing Company             Imperial IPA  11.00  4.65   
2         Russian River Brewing Company             Imperial IPA   8.00  4.64   
3              Founder