In [21]:
%pylab inline
from matplotlib import pyplot as plt
clf = tree.DecisionTreeClassifier()

Populating the interactive namespace from numpy and matplotlib


In [22]:
from sklearn import datasets, metrics, tree, cross_validation

In [23]:
iris = datasets.load_iris()

In [24]:
# instance of a tree
myTree = tree.DecisionTreeClassifier()

In [25]:
# fitting the model

In [26]:
myTree_fit = myTree.fit(iris.data, iris.target)

In [27]:
# thats it!! amazeballs

In [28]:
y_pred = myTree_fit.predict(iris.data) # this is totally wrong becuse we are using the model data to test it!

In [29]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [30]:
#how did we do!!
print("number of mislabelled points %d" % (iris.target != y_pred).sum())

number of mislabelled points 0


In [31]:
print("absolutly ridiculous overfit score: %d" % (myTree_fit.score(iris.data, iris.target)))

absolutly ridiculous overfit score: 1


In [32]:
#lets look at the confusion matrix
metrics.confusion_matrix(iris.target, y_pred)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]])

In [33]:
# lets look at something else 
print metrics.classification_report(iris.target, y_pred)

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       1.00      1.00      1.00        50
          2       1.00      1.00      1.00        50

avg / total       1.00      1.00      1.00       150



In [34]:
#Generalizing our tree
# As mentioned before, having a perfect model is more often scary. 
#We know this is overfitting by using a test/train set ...from iris

In [35]:
# the below line cross validates in a single line!!!! 

In [39]:
# (clf is just another tree object)

In [40]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(iris.data, iris.target, test_size=.3)
clf.fit(x_train, y_train)

DecisionTreeClassifier(compute_importances=None, criterion='gini',
            max_depth=None, max_features=None, max_leaf_nodes=None,
            min_density=None, min_samples_leaf=1, min_samples_split=2,
            random_state=None, splitter='best')

In [41]:
metrics.confusion_matrix(y_train, clf.predict(x_train))

array([[39,  0,  0],
       [ 0, 32,  0],
       [ 0,  0, 34]])

In [42]:
print metrics.classification_report(y_train,clf.predict(x_train))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        39
          1       1.00      1.00      1.00        32
          2       1.00      1.00      1.00        34

avg / total       1.00      1.00      1.00       105



In [43]:
metrics.confusion_matrix(y_test, clf.predict(x_test))

array([[11,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 16]])

In [44]:
print metrics.classification_report(y_test,clf.predict(x_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      0.94      0.97        18
          2       0.94      1.00      0.97        16

avg / total       0.98      0.98      0.98        45



In [45]:
#Though the concept of "pruning" is not as clear in sklearn
#(specifically since decision trees are only included as a 
#"well-known" model), we can generalize the model by changing
#the defaults of min_samples_leaf and max_depth.

In [46]:
clf.set_params(min_samples_leaf=5) # this limits the leaves to 5
clf.set_params(max_depth=5) # this is the number of levels in the tree
clf.fit(x_train, y_train)
metrics.confusion_matrix(y_train, clf.predict(x_train))
metrics.confusion_matrix(y_test, clf.predict(x_test))

array([[11,  0,  0],
       [ 0, 16,  2],
       [ 0,  0, 16]])

In [47]:
# lets use pydot to make a wicked tree
import StringIO

In [49]:
# lets install pydot! this is a pipe that connects python to the dot language
import pydot
import pyparsing

In [50]:
dot_data = StringIO.StringIO()
tree.export_graphviz(myTree_fit, out_file=dot_data)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf('iris_decisiontree.pdf')
print '\nimage created'


image created


In [51]:
pwd

u'/Users/nickroot/Desktop/Python'